dataset:
  dataset_source: webdataset
  manifest_path: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/data/datasets/custom/train-*.tar
  webdataset_urls: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/data/datasets/FMVC/train-*.tar
  num_samples: 64
  num_reference_images: 3
  video_num_frames: 81
  video_frame_stride: 1
  video_height: 448
  video_width: 448
  vis_image_size: 448
  geo_image_size: 448
  max_text_length: 512
  shuffle: false
  num_workers: 1
  prefetch_factor: 1
  pin_memory: true
  persistent_workers: false

optimizer:
  learning_rate: 2.0e-5
  lr_schedule: constant
  weight_decay: 0.01
  betas: [0.9, 0.95]
  eps: 1.0e-8
  max_grad_norm: 1.0
  warmup_steps: 20

training:
  output_dir: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/DeepWorld/exps/demo
  seed: 42
  num_epochs: 300
  per_device_batch_size: 1
  gradient_accumulation_steps: 2
  log_every: 1
  save_every: 400
  eval_num_samples: 8
  mixed_precision: bf16
  use_fsdp: true
  gradient_checkpointing: true

qwen_brain:
  checkpoint_path: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/data/models/Qwen3-VL-8B-Instruct
  transformer_dtype: bfloat16
  vggt_checkpoint_path: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/data/models/VGGT-1B
  vggt_dtype: null
  lora_rank: 64
  lora_alpha: null
  lora_dropout: 0.05
  lora_target_modules: [q_proj, k_proj, v_proj, o_proj]
  routed_ffn_mode: lora
  routed_ffn_lora_rank: 256
  routed_ffn_lora_alpha: null
  routed_ffn_lora_dropout: 0.05

wan_renderer:
  checkpoint_path: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/data/models/Wan2.1-T2V-1.3B
  transformer_dtype: bfloat16
  vae_dtype: null
  vae_enable_slicing: true
  vae_enable_tiling: true
  vae_sample_posterior: false
  train_scheduler_steps: 1000
  inference_steps: 30
