dataset:
  dataset_source: webdataset
  manifest_path: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/data/datasets/custom/train-*.tar
  webdataset_urls: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/data/datasets/FMVC/train-*.tar
  num_samples: 800
  num_reference_images: 3
  video_num_frames: 121
  video_frame_stride: 1
  video_height: 448
  video_width: 448
  vis_image_size: 448
  geo_image_size: 448
  max_text_length: 512
  shuffle: false
  num_workers: 1
  prefetch_factor: 1
  pin_memory: true
  persistent_workers: true

optimizer:
  learning_rate: 1.0e-5
  brain_language_model_learning_rate: 3.0e-5
  brain_others_learning_rate: 5.0e-5
  renderer_transformer_learning_rate: 1.0e-5
  renderer_others_learning_rate: 5.0e-5
  lr_schedule: constant
  weight_decay: 0.01
  betas: [0.9, 0.95]
  eps: 1.0e-8
  max_grad_norm: 1.0
  warmup_steps: 20

training:
  output_dir: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/DeepWorld/exps/demo
  seed: 42
  max_total_epochs: 30
  max_total_steps: 1500
  per_device_batch_size: 1
  renderer_batch_multiplier: 4
  gradient_accumulation_steps: 2
  log_every: 1
  save_every: 300
  eval_num_samples: 8
  mixed_precision: bf16
  use_fsdp: true
  gradient_checkpointing: true
  pretrained_model_path: null

qwen_brain:
  checkpoint_path: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/data/models/Qwen3-VL-8B-Instruct
  transformer_dtype: bfloat16
  vggt_checkpoint_path: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/data/models/VGGT-1B
  vggt_dtype: null
  lora_rank: 64
  lora_alpha: null
  lora_dropout: 0.05
  lora_target_modules: [q_proj, k_proj, v_proj, o_proj]
  routed_ffn_mode: lora
  routed_ffn_lora_rank: 256
  routed_ffn_lora_alpha: null
  routed_ffn_lora_dropout: 0.05

wan_renderer:
  checkpoint_path: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/data/models/Wan2.2-TI2V-5B-Diffusers
  transformer_dtype: bfloat16
  vae_dtype: float32
  vae_enable_slicing: true
  vae_enable_tiling: true
  vae_sample_posterior: false
  condition_injection_mode: input_addition
  condition_proj_init: normal
  condition_proj_init_std: null
  condition_dropout_prob: 0.1
  train_scheduler_steps: 1000
  inference_steps: 25
