dataset:
  manifest_path: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/data/datasets/DeepWorld/manifest_train.jsonl
  eval_manifest_path: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/data/datasets/DeepWorld/manifest_val.jsonl
  data_root: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/data/datasets/DeepWorld
  num_samples: 800
  video_width: 448
  video_height: 448
  video_fps: 24
  video_duration: 5.0
  prompt_rich_prob: 0.5
  prompt_medium_prob: 0.3
  prompt_coarse_prob: 0.2
  mixing_t2v_prob: 0.0
  vis_image_size: 448
  geo_image_size: 448
  max_text_length: 512
  eval_num_samples: 8
  shuffle: false
  num_workers: 1
  prefetch_factor: 1
  pin_memory: true
  persistent_workers: true
optimizer:
  learning_rate: 1.0e-05
  brain_language_model_learning_rate: 3.0e-05
  brain_others_learning_rate: 5.0e-05
  renderer_transformer_learning_rate: 1.0e-05
  renderer_others_learning_rate: 5.0e-05
  lr_schedule: constant
  weight_decay: 0.01
  betas:
    - 0.9
    - 0.95
  eps: 1.0e-08
  max_grad_norm: 1.0
  warmup_steps: 20
training:
  output_dir: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/DeepWorld/exps/demo
  seed: 20021021
  max_total_epochs: 30
  max_total_steps: 1500
  gradient_accumulation_steps: 2
  log_every: 1
  eval_every: 300
  save_every: 300
  mixed_precision: bf16
  use_fsdp: true
  gradient_checkpointing: true
  pretrained_model_path: null
brain:
  checkpoint_path: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/data/models/Qwen3-VL-8B-Instruct
  transformer_dtype: bfloat16
  vggt_checkpoint_path: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/data/models/VGGT-1B
  vggt_dtype: null
  lora_rank: 64
  lora_alpha: null
  lora_dropout: 0.05
  lora_target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
  routed_ffn_mode: lora
  routed_ffn_lora_rank: 256
  routed_ffn_lora_alpha: null
  routed_ffn_lora_dropout: 0.05
renderer:
  checkpoint_path: /home/hadoop-intelligence-studio/dolphinfs_ssd_hadoop-intelligence-studio/songbaijun/data/models/Wan2.2-TI2V-5B-Diffusers
  transformer_dtype: bfloat16
  vae_dtype: float32
  vae_enable_slicing: true
  vae_enable_tiling: true
  vae_sample_posterior: false
  condition_injection_mode: input_addition
  condition_proj_init: normal
  condition_proj_init_std: null
  condition_dropout_prob: 0.1
  train_scheduler_steps: 1000
  inference_steps: 25
